# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anais Hristea Portfolio
email: hristeaanais@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Artsy coder, I am enthusiastic of the human side of technology and a student in Computing at University of Greenwich. I am looking for broadening my ability to emphasise humanity using machines, lately interested in using UX and VR in this intent.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: HrAnais
github_username:  HSAnais

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
