# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anais Hristea Portfolio
email: hristeaanais@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Creative technologist curious about the human side of technology, I am currently working as UX & Interaction Designer at Transforming Systems, in London. As a UX Designer, I view digital accessibility being the perfect case to explore the spectrum of user interactions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: HrAnais
github_username:  HSAnais

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
